// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52UHAO5S63qCcAItOT-SR6wHsTMPq29o',
    appId: '1:671476633370:web:7be22dc3f51219fafda6a3',
    messagingSenderId: '671476633370',
    projectId: 'weight-calendar-project',
    authDomain: 'weight-calendar-project.firebaseapp.com',
    storageBucket: 'weight-calendar-project.appspot.com',
    measurementId: 'G-GBP7Z5CV1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlikzQfcUC76EaYmpmH9PVDu_os1A9zys',
    appId: '1:671476633370:android:d8a72237121eec9bfda6a3',
    messagingSenderId: '671476633370',
    projectId: 'weight-calendar-project',
    storageBucket: 'weight-calendar-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANyhKasy8Kf6KtdlWmymYdYIjm_ZE0q3Q',
    appId: '1:671476633370:ios:ea01047f91fc62fffda6a3',
    messagingSenderId: '671476633370',
    projectId: 'weight-calendar-project',
    storageBucket: 'weight-calendar-project.appspot.com',
    iosBundleId: 'com.kthdd.weightCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANyhKasy8Kf6KtdlWmymYdYIjm_ZE0q3Q',
    appId: '1:671476633370:ios:c9b9ae4f75f2696efda6a3',
    messagingSenderId: '671476633370',
    projectId: 'weight-calendar-project',
    storageBucket: 'weight-calendar-project.appspot.com',
    iosBundleId: 'com.kthdd.myWeightApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB52UHAO5S63qCcAItOT-SR6wHsTMPq29o',
    appId: '1:671476633370:web:3ffb1e9df62ea41ffda6a3',
    messagingSenderId: '671476633370',
    projectId: 'weight-calendar-project',
    authDomain: 'weight-calendar-project.firebaseapp.com',
    storageBucket: 'weight-calendar-project.appspot.com',
    measurementId: 'G-GL3D60K2CT',
  );
}
